import crypto from 'crypto';
import { Resend } from 'resend';

const resendKey = process.env.RESEND_API_KEY;
const resend = resendKey ? new Resend(resendKey) : null;

const FROM = process.env.EMAIL_FROM || 'DogText <hello@dogtext.app>';
const BASE_URL =
  process.env.NEXTAUTH_URL?.replace(/\/$/, '') || 'https://dogtext-tau.vercel.app';

function unsubToken(userId: string): string {
  const secret = process.env.NEXTAUTH_SECRET || 'dev-only-secret';
  return crypto.createHmac('sha256', secret).update(userId).digest('hex').slice(0, 32);
}

export function verifyUnsubToken(userId: string, token: string): boolean {
  const expected = unsubToken(userId);
  if (expected.length !== token.length) return false;
  return crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(token));
}

interface DailyBarkEmail {
  to: string;
  userId: string;
  dogName: string;
  dogBreed: string;
  messageText: string;
  barkId: string;
}

export async function sendDailyBarkEmail(args: DailyBarkEmail): Promise<
  { ok: true; id: string } | { ok: false; error: string }
> {
  if (!resend) {
    return { ok: false, error: 'RESEND_API_KEY not configured' };
  }

  const { to, userId, dogName, dogBreed, messageText, barkId } = args;
  const unsubUrl = `${BASE_URL}/api/unsubscribe?u=${userId}&t=${unsubToken(userId)}`;
  const shareUrl = `${BASE_URL}/bark/${barkId}`;

  const formatted = messageText
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0);

  const html = `<!doctype html>
<html>
  <body style="margin:0;padding:0;background:#FFF8F0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;color:#2C2C2C;">
    <div style="max-width:560px;margin:0 auto;padding:32px 16px;">
      <div style="text-align:center;margin-bottom:24px;">
        <a href="${BASE_URL}" style="text-decoration:none;color:#FF8C42;font-size:20px;font-weight:700;">🐕 DogText</a>
      </div>
      <div style="background:#fff;border-radius:24px;padding:28px;box-shadow:0 8px 32px rgba(0,0,0,0.06);">
        <div style="display:flex;align-items:center;gap:12px;padding-bottom:16px;border-bottom:1px solid #f0f0f0;">
          <div style="width:48px;height:48px;border-radius:24px;background:linear-gradient(135deg,#FF8C42,#FFB380);display:inline-block;text-align:center;line-height:48px;font-size:24px;">🐕</div>
          <div>
            <div style="font-weight:600;font-size:16px;color:#2C2C2C;">${dogName}</div>
            <div style="font-size:12px;color:#888;">your dog · ${dogBreed}</div>
          </div>
        </div>
        <div style="padding-top:20px;">
          <div style="text-align:center;font-size:11px;color:#aaa;margin-bottom:12px;">Today</div>
          ${formatted
            .map(
              (line) =>
                `<div style="background:#f4f4f4;border-radius:18px;border-top-left-radius:4px;padding:14px 18px;margin-bottom:10px;font-size:15px;line-height:1.5;color:#2C2C2C;">${escapeHtml(line)}</div>`,
            )
            .join('')}
        </div>
        <div style="margin-top:24px;text-align:center;">
          <a href="${shareUrl}" style="display:inline-block;background:#FF8C42;color:#fff;text-decoration:none;padding:12px 28px;border-radius:999px;font-weight:600;font-size:14px;">Share ${dogName}'s text</a>
        </div>
      </div>
      <div style="text-align:center;margin-top:24px;font-size:12px;color:#999;line-height:1.6;">
        Generated by AI based on ${dogName}'s breed and personality.<br/>
        Real dog. Not a real text.<br/><br/>
        <a href="${BASE_URL}/dashboard" style="color:#888;text-decoration:underline;">Open dashboard</a>
        &nbsp;·&nbsp;
        <a href="${unsubUrl}" style="color:#888;text-decoration:underline;">Unsubscribe</a>
      </div>
    </div>
  </body>
</html>`;

  const text = [
    `${dogName} (your ${dogBreed}) sent you a text:`,
    '',
    ...formatted,
    '',
    `Share: ${shareUrl}`,
    `Unsubscribe: ${unsubUrl}`,
  ].join('\n');

  try {
    const result = await resend.emails.send({
      from: FROM,
      to,
      subject: `${dogName} sent you a text 🐕`,
      html,
      text,
      headers: { 'List-Unsubscribe': `<${unsubUrl}>` },
    });
    if (result.error) {
      return { ok: false, error: result.error.message };
    }
    return { ok: true, id: result.data?.id ?? '' };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'unknown' };
  }
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
