import Link from 'next/link';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import { prisma } from '@/lib/db';
import { Heart, Sparkles } from 'lucide-react';

export const dynamic = 'force-dynamic';

async function loadBark(id: string) {
  try {
    return await prisma.dailyBark.findUnique({
      where: { id },
      include: {
        dog: { select: { name: true, breed: true, photoUrl: true } },
      },
    });
  } catch {
    return null;
  }
}

export async function generateMetadata({ params }: { params: { id: string } }) {
  const bark = await loadBark(params.id);
  if (!bark) return { title: 'Bark not found | DogText' };
  return {
    title: `${bark.dog.name} sent a text — DogText`,
    description: bark.messageText,
    openGraph: {
      title: `${bark.dog.name}, ${bark.dog.breed}`,
      description: bark.messageText,
      type: 'article',
    },
    twitter: {
      card: 'summary_large_image',
      title: `${bark.dog.name} sent a text`,
      description: bark.messageText,
    },
  };
}

export default async function PublicBarkPage({ params }: { params: { id: string } }) {
  const bark = await loadBark(params.id);
  if (!bark) notFound();

  prisma.dailyBark
    .update({ where: { id: bark.id }, data: { shareCount: { increment: 1 } } })
    .catch(() => {});

  const dateLabel = new Date(bark.generatedFor).toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
    timeZone: 'UTC',
  });

  return (
    <div className="min-h-screen bg-gradient-to-b from-[#FFF8F0] to-white py-12 px-4">
      <div className="max-w-xl mx-auto">
        <div className="text-center mb-8">
          <Link href="/" className="inline-flex items-center gap-2">
            <div className="w-10 h-10 bg-[#FF8C42] rounded-lg flex items-center justify-center">
              <Heart className="w-6 h-6 text-white" />
            </div>
            <span className="text-2xl font-bold text-gray-900">DogText</span>
          </Link>
        </div>

        <div className="bg-white rounded-3xl shadow-2xl p-8 border border-gray-100">
          <div className="flex items-center gap-4 mb-6">
            <div className="relative w-16 h-16 rounded-full overflow-hidden bg-[#FFF8F0] ring-2 ring-[#FF8C42] ring-offset-2 shrink-0">
              {bark.dog.photoUrl ? (
                <Image
                  src={bark.dog.photoUrl}
                  alt={bark.dog.name}
                  fill
                  sizes="64px"
                  className="object-cover"
                />
              ) : (
                <div className="w-full h-full flex items-center justify-center text-2xl font-bold text-[#FF8C42]">
                  {bark.dog.name.charAt(0)}
                </div>
              )}
            </div>
            <div className="flex-1 min-w-0">
              <h1 className="text-2xl font-bold text-gray-900">{bark.dog.name}</h1>
              <p className="text-sm text-gray-600">{bark.dog.breed}</p>
              <p className="text-xs text-[#FF8C42] font-medium inline-flex items-center gap-1 mt-1">
                <Sparkles className="w-3 h-3" />
                Daily Bark · {dateLabel}
              </p>
            </div>
          </div>

          <div className="bg-gradient-to-br from-[#FFB88C] to-[#FFB6C1] text-white p-6 rounded-3xl rounded-tl-sm shadow-md mb-6">
            <p className="text-xl leading-relaxed font-medium">{bark.messageText}</p>
          </div>

          <div className="text-center">
            <p className="text-sm text-gray-600 mb-4">
              Get a daily message like this from your own dog.
            </p>
            <Link
              href="/auth/signup"
              className="inline-block bg-[#FF8C42] hover:bg-[#FF6B1A] text-white font-semibold px-6 py-3 rounded-full transition-colors shadow-md"
            >
              Try DogText free
            </Link>
            <p className="text-xs text-gray-400 mt-3">
              Free forever — 5 chats a week, plus a daily bark.
            </p>
          </div>
        </div>

        <p className="text-center text-xs text-gray-400 mt-6">
          Generated by AI based on {bark.dog.name}'s breed and personality. Real dog. Not real text.
        </p>
      </div>
    </div>
  );
}
